package icepunk_backend.service;
import icepunk_backend.model.*; import icepunk_backend.dto.GenerationRequest; import icepunk_backend.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*; import java.time.OffsetDateTime; import java.util.*;
@Service public class GeneratedPackTransactionService {
 private final GeneratedPackRepository packs; private final GeneratedPackItemRepository items;
 public GeneratedPackTransactionService(GeneratedPackRepository packs, GeneratedPackItemRepository items){this.packs=packs;this.items=items;}
 @Transactional(propagation=Propagation.REQUIRES_NEW) public Context createPendingPack(User owner, GenerationRequest r, List<java.nio.file.Path> files){ UUID id=UUID.randomUUID(), ns=UUID.randomUUID(); GeneratedPack p=new GeneratedPack();p.setId(id);p.setOwner(owner);p.setName(r.getPackName()==null||r.getPackName().isBlank()?"IcePunk Pack":r.getPackName().trim());p.setSourceType(GenerationSourceType.valueOf(r.getSource().name()));p.setGenerationType(GeneratedPackType.valueOf(r.getType().name()));p.setAmount(r.getAmount());p.setVisibility(r.getPublishMode()==GenerationRequest.PublishMode.PRIVATE?GeneratedPackVisibility.PRIVATE:GeneratedPackVisibility.PUBLIC);p.setStatus(GeneratedPackStatus.PENDING);p.setZipObjectKey("generated-packs/"+ns+"/archive/"+UUID.randomUUID()+".zip");p.setCreatedAt(OffsetDateTime.now());packs.save(p); List<Item> out=new ArrayList<>(); for(int i=0;i<files.size();i++){GeneratedPackItem x=new GeneratedPackItem();x.setId(UUID.randomUUID());x.setPack(p);x.setItemIndex(i);x.setFileName(files.get(i).getFileName().toString());String key="generated-packs/"+ns+"/items/"+x.getId()+".mid";x.setMidiObjectKey(key);x.setCreatedAt(p.getCreatedAt());items.save(x);out.add(new Item(x.getId(),key));} packs.flush(); return new Context(id,p.getZipObjectKey(),out);}
 @Transactional(propagation=Propagation.REQUIRES_NEW) public boolean finalizeReady(UUID id){return packs.markReadyIfPending(id)==1;}
 @Transactional(propagation=Propagation.REQUIRES_NEW) public void markFailedIfPending(UUID id,String code){packs.findById(id).filter(p->p.getStatus()==GeneratedPackStatus.PENDING).ifPresent(p->{p.setStatus(GeneratedPackStatus.FAILED);p.setFailureCode(code);p.setUpdatedAt(OffsetDateTime.now());packs.save(p);});}
 public record Context(UUID packId,String zipKey,List<Item> items){} public record Item(UUID id,String key){}
}
