spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/icepunk
spring.datasource.username=icepunk
spring.datasource.password=icepunk

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true