spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/icepunk
spring.datasource.username=icepunk
spring.datasource.password=icepunk

jwt.secret=icepunk-super-secret-key-icepunk-super-secret-key
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

s3.endpoint=http://localhost:9010
s3.region=eu-central-1
s3.bucket=icepunk-zips
s3.access-key=minioadmin
s3.secret-key=minioadmin
s3.public-url=http://localhost:9010/icepunk-zips